Bugfix/excluding diqualified by during update
Netflix/repokid pull request #290
Opened 2021-06-08 14:28 UTC by guilhermesenazuza

We started to use Repokid internally at FollowAnalytics and we found a weird behavior when playing with the filters.
In this PR we propose to share the changes we made in our forked project.
Bellow I'll describe how you can reproduce it:

1. Add a filter in the config file to disqualify your test role (we'll call it RoleTest), you can use age filter for example.
2. Run the command to update the role cache and verify that the _disqualified by_ list is not empty for RoleTest.
3. Change the config file to make the RoleTest eligible.
4. Run the command to update the role cache.
5. The expected is to have an empty list in _disqualified by_ but it keeps the filter applied previously.

In this PR we propose to reset the _disqualified by_ list before the filter application. We also added the function _calculate_repo_scores_ to have the repoable policies of the roles recently became eligible during the filter application.

2021-06-08 18:25 UTC, patricksanders approved these changes
Thanks for the PR! This looks good to me.

2021-06-08 20:54 UTC, patricksanders requested changes
Whoops, approved too soon. Can you please run `black` on this file so the build passes?

2021-06-09 07:52 UTC, guilhermesenazuza commented
Sure, it's done

2021-06-09 16:57 UTC, patricksanders approved these changes

2021-06-09 16:57 UTC, patricksanders commented
Thanks @guilhermesenazuza!

2021-06-09 16:57 UTC, merged